### ISSUE TITLE
Clean up groups request to use filters

### ISSUE THREAD

**Issue by nitnelave** [nitnelave/lldap#103]
Rather than rely on ad-hoc code to delegate to list_groups, list_user's_groups and so on.

**Comment by lowinger42** [comment]
I have tried to activate Librenms LDAP support against lldap.
The user bind is successful, then Librenms tries to verify group membership to grant permissions (admin, global_read, normal).
There are three ways to "find group members by"
- Username
- Full DN (using prefix and suffix)
- DN Search (search using uid attribute)

None of these works. Debug log when using Username:

lldap_1 | 2022-01-23T22:39:26.440636Z DEBUG lldap::infra::ldap_handler: Received search request: LdapSearchRequest { base: "ou=groups,dc=int,dc=abundo,dc=se", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: And([Equality("cn", "librenms_admin"), Equality("uniqueMember", "")]), attrs: [] }

lldap_1 | 2022-01-23T22:39:26.441122Z DEBUG lldap::infra::ldap_server: Replying with LDAP op: SearchResultDone(LdapResult { code: UnwillingToPerform, matcheddn: "", message: "Unsupported group filter: Unsupported group filter: Equality(\"cn\", \"librenms_admin\")", referral: [] })

**Comment by nitnelave** [comment]
@lowinger42 can you try getting Librenms to work with the latest docker image?
