### ISSUE TITLE
Nextcloud tutorial

### ISSUE THREAD

**Issue by Sblop** [nitnelave/lldap#107]
Hi,

First of all, thanks for this. It is great, and I look forward to more features, like being able to see logs in the webinterface etc.

I have configured Authelia and it works great. I do however have some problems with Nextcloud.
It connect to the server, and gets "green".
As with authelia I use same login
cn=admin,ou=people,dc=xxx-xxx,dc=xx
and base DN
ou=people,dc=xxx-xxx,dc=xx
It are able to detect 2 users. Great. However when ever I try to be specific and check a specific user I get:

`[PHP] Error: ldap_search(): Search: Server is unwilling to perform at /config/www/nextcloud/apps/user_ldap/lib/LDAP.php#336

POST /apps/user_ldap/ajax/wizard.php
from MY.IP.IP.IP by My.Name at 2021-12-06T09:52:01+00:00`

Full test from log: (Sorry about the crappy formatting...)

`{"reqId":"te5Gyh7vo33lGkLnJNse","level":3,"time":"2021-12-06T09:52:01+00:00","remoteAddr":"MY.IP.IP.IP","user":"MY.NAME","app":"PHP","method":"POST","url":"/apps/user_ldap/ajax/wizard.php","message":"ldap_search(): Search: Server is unwilling to perform at /config/www/nextcloud/apps/user_ldap/lib/LDAP.php#336","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"ldap_search(): Search: Server is unwilling to perform at /config/www/nextcloud/apps/user_ldap/lib/LDAP.php#336","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/user_ldap/lib/LDAP.php","line":224,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"function":"OCA\\User_LDAP\\{closure}","class":"OCA\\User_LDAP\\LDAP","type":"->","args":["*** sensitive parameters replaced ***"]},{"function":"ldap_search"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/LDAP.php","line":336,"function":"call_user_func_array"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/LDAP.php","line":229,"function":"invokeLDAPMethod","class":"OCA\\User_LDAP\\LDAP","type":"->","args":["*** sensitive parameters replaced ***"]},{"function":"search","class":"OCA\\User_LDAP\\LDAP","type":"->"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Access.php","line":1113,"function":"call_user_func_array"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Access.php","line":1117,"function":"OCA\\User_LDAP\\{closure}","class":"OCA\\User_LDAP\\Access","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Access.php","line":1175,"function":"invokeLDAPMethod","class":"OCA\\User_LDAP\\Access","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Access.php","line":1280,"function":"executeSearch","class":"OCA\\User_LDAP\\Access","type":"->"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Access.php","line":1026,"function":"count","class":"OCA\\User_LDAP\\Access","type":"->"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Access.php","line":887,"function":"countUsers","class":"OCA\\User_LDAP\\Access","type":"->"},{"file":"/config/www/nextcloud/apps/user_ldap/lib/Wizard.php","line":657,"function":"countUsersByLoginName","class":"OCA\\User_LDAP\\Access","type":"->"},{"file":"/config/www/nextcloud/apps/user_ldap/ajax/wizard.php","line":112,"function":"testLoginName","class":"OCA\\User_LDAP\\Wizard","type":"->"},{"file":"/config/www/nextcloud/lib/private/Route/Route.php","line":155,"args":["/config/www/nextcloud/apps/user_ldap/ajax/wizard.php"],"function":"require_once"},{"function":"OC\\Route\\{closure}","class":"OC\\Route\\Route","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":310,"function":"call_user_func"},{"file":"/config/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/config/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61addd9ca0c7a"}`

I have been trying all weekend, and I expect this to be my mistake, as I am only just learning to get my head around LDAP...

Edit: Removed IP etc.

**Comment by nitnelave** [comment]
Hey! Thanks for the report :) We talked about that on Discord this weekend with QuiteReel, NextCloud is requesting an unexpected parameter "entryUUID" (so it's an LLDAP problem, not your fault).

I know what to do, it's just a matter of finding the time. Right now I'm mostly working on #47 , but as soon as I'm done with that I'll get cracking on this one.

**Comment by Sblop** [comment]
Thanks for your swift reply. I do not want to push, so take your time. Great project, and best of luct with everything.
For now, I will hold my horses, until next version :-)
Thanks again.

**Comment by nitnelave** [comment]
Someone sent me a working nextcloud configuration, I just have to format it nicely and put it up

**Comment by rasmus91** [comment]
Nextcloud login via LLDAP working fine here, but as we discussed on discord, there are some difficulties in changing the password from nextcloud, even if the user nextcloud uses is in the password manager group.
