### ISSUE TITLE
Mealie LDAP Failing Authentication

### ISSUE THREAD

**Issue by abbiewade** [nitnelave/lldap#115]
Hi @nitnelave! 

I'm running the standard [mealie](https://hay-kot.github.io/mealie/documentation/getting-started/install/#docker-compose-with-sqlite) setup and struggling to get it to authenticate with LLDAP. 

The extra environment variables I am using are: 
```
LDAP_AUTH_ENABLED: "True"
LDAP_SERVER_URL: ldap://lldap:3890
LDAP_BIND_TEMPLATE: cn={},ou=people,dc=example,dc=com
LDAP_ADMIN_FILTER(member=cn=admins,ou=groups,dc=example,dc=com)
```

I'm not certain this one is hitting lldap at all, but struggling to work out what is going wrong. 

Thanks in advance!

**Comment by abbiewade** [comment]
After some digging into Mealie, I stumbled across [this comment on a PR they did when implementing LDAP](https://github.com/hay-kot/mealie/pull/803#issuecomment-1007591426). This quote nicely sums it up.

>  Instead of using a service account to find the appropriate account, it directly gets its DN by templating a string (e.g. cn={},dc=example,dc=com turns into cn=dvdkon,dc=example,dc=com if I'm logging in).

What this means for lldap, is we can't use their `ADMIN_FILTER` check because we don't have permissions. 

the python error we get is: 
```
INSUFFICIENT_ACCESS: {'msgtype': 101, 'msgid': 3, 'result': 50, 'desc': 'Insufficient access', 'ctrls': [], 'info': 'Current user `cn=abbie,ou=people,dc=example,dc=com` is not allowed to query LDAP, expected cn=admin,ou=people,dc=example,dc=com'}
``` 

the lldap error is: 
```
lldap             | 2022-02-01T11:29:53.537756Z DEBUG lldap::infra::ldap_server: Received LDAP message: LdapMsg { msgid: 2, op: SearchRequest(LdapSearchRequest { base: "cn=abbie,ou=people,dc=example,dc=com", scope: Base, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: Equality("memberOf", "cn=admins,ou=groups,dc=example,dc=com"), attrs: [] }), ctrl: [] }    
lldap             | 2022-02-01T11:29:53.537819Z DEBUG lldap::infra::ldap_server: Replying with LDAP op: SearchResultDone(LdapResult { code: InsufficentAccessRights, matcheddn: "", message: "Current user `cn=abbie,ou=people,dc=example,dc=com` is not allowed to query LDAP, expected cn=admin,ou=people,dc=example,dc=com", referral: [] })    
```
Is this something we can get LLDAP to be able to handle?

**Comment by nitnelave** [comment]
Hmm... It's by design that users cannot ask for the list of users in a group (access control). However, you should be able to get the list of groups you're in. Maybe mealie doesn't support that? See the other issue in LLDAP about refactoring group filters, it doesn't currently work for some combination of filters.

**Comment by nitnelave** [comment]
I guess as a workaround, I could allow users to list groups, but limit their query to the groups that the user is part of.
