### ISSUE TITLE
Improve looks

### ISSUE THREAD

**Issue by nitnelave** [nitnelave/lldap#12]
All about making it pretty!

- [ ] Logo
- [x] Proper HTML structure
- [x] CSS classes
- [ ] Images, banners, ...

**Comment by matthewstrasiotto** [comment]
I'm happy enough to take a crack at this, btw. 
Looks are okay, but mobile interface could be improved

**Comment by nitnelave** [comment]
That would be much appreciated, frontend work is not my strong suit.

**Comment by matthewstrasiotto** [comment]
> That would be much appreciated, frontend work is not my strong suit.

I like frontend work, and I should be able to fix up at least the bootstrap so it works on more viewports, and I'm excited to play with `yew`
