### ISSUE TITLE
nginx-auth-ldap client

### ISSUE THREAD

**Issue by Cyrix126** [nitnelave/lldap#120]
Trying to get https://github.com/kvspb/nginx-auth-ldap to work.

Here's my block in nginx.conf, I think I'm getting close.
domain name replaced. I should add that the domain name has a dash like this: nom-domaine
```
ldap_server ldaplocal {
        url ldap://localhost:389/dc=domain,dc=com?(&(uid=${admin})&(objectClass=people));
        binddn "cn=admin,ou=people,dc=domain,dc=com";
        binddn_passwd "nottruepassword";
        group_attribute lldap_admin;
        group_attribute_is_dn on;
        require valid_user;
        referral off;
      }
```

error in log/nginx/error.log
```
2022/02/20 19:29:46 [notice] 4051002#4051002: http_auth_ldap: parse_require in /etc/nginx/nginx.conf:63
2022/02/20 19:29:47 [notice] 4051003#4051003: http_auth_ldap: parse_require in /etc/nginx/nginx.conf:63
2022/02/20 19:29:47 [error] 4051006#4051006: http_auth_ldap: Could not connect
2022/02/20 19:29:47 [error] 4051012#4051012: http_auth_ldap: Could not connect
2022/02/20 19:29:57 [error] 4051006#4051006: http_auth_ldap: Could not connect
2022/02/20 19:30:07 [error] 4051006#4051006: http_auth_ldap: Could not connect
```
log in lldap (for some reason the date time is -1h, not getting the local timezone ?)
```
2022-02-20T18:29:47.217439Z DEBUG lldap::infra::ldap_server: Received LDAP message: LdapMsg { msgid: 1, op: BindRequest(LdapBindRequest { dn: "cn=admin,ou=people,dc=domain,dc=com", cred: Simple("********") }), ctrl: [] }    
2022-02-20T18:29:47.217556Z DEBUG lldap::infra::ldap_handler: Received bind request for "cn=admin,ou=people,dc=domain,dc=com"    
2022-02-20T18:29:47.217696Z DEBUG lldap::infra::ldap_server: Replying with LDAP op: BindResponse(LdapBindResponse { res: LdapResult { code: Success, matcheddn: "", message: "", referral: [] }, saslcreds: None })
```

**Comment by nitnelave** [comment]
Hmm, that's weird. It seems that LLDAP is replying as expected, but nginx (or the plugin) doesn't get or cannot read the response? I'd capture the traffic to/from nginx on that port with tcpdump and talk to the plugin owner. You can link to this issue for conversation as well, or if there's actually something wrong with the LLDAP answer.

**Comment by Cyrix126** [comment]
Actually the connection is fine, I just had to restart nginx to get those error log disappear, reload wasn't sufficient.

Now with debug in nginx log I understand that the line posing issue is the filter.
The filter `(&(uid=${admin})&(objectClass=people))` generate those lines in nginx log:

```
http_auth_ldap: Search filter is "(&(objectClass=*)((&(uid=${admin})&(objectClass=people))=test))"
http_auth_ldap: ldap_search_ext() failed (-7, Bad search filter), client: 192.168.1.1, server: domain.com, request: " GET / HTTP/1.0", host: "domain.com"
```
If I use `?uid?sub?(objectClass=posixAccount)` and post a request with user test, lldap respond:

```
2022-02-26T08:35:37.553782Z DEBUG lldap::infra::ldap_server: Received LDAP message: LdapMsg { msgid: 2, op: SearchRequest(LdapSearchRequest { base: "ou=people,dc=domain,dc=com", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: And([Equality("objectClass", "posixAccount"), Equality("uid", "test")]), attrs: ["1.1"] }), ctrl: [] }    
2022-02-26T08:35:37.553896Z DEBUG lldap::infra::ldap_handler: Received search request: LdapSearchRequest { base: "ou=people,dc=domain,dc=com", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: And([Equality("objectClass", "posixAccount"), Equality("uid", "test")]), attrs: ["1.1"] }    
2022-02-26T08:35:37.555156Z  INFO sqlx::query: SELECT `users`.`user_id`, `email`, `users`.`display_name`, …; rows: 1, elapsed: 447.427µs

SELECT
  `users`.`user_id`,
  `email`,
  `users`.`display_name`,
  `first_name`,
  `last_name`,
  `avatar`,
  `creation_date`
FROM
  `users`
WHERE
  TRUE
  AND (`users`.`user_id` = 'test')
ORDER BY
  `users`.`user_id` ASC
  
2022-02-26T08:35:37.555298Z DEBUG lldap::infra::ldap_server: Replying with LDAP op: SearchResultDone(LdapResult { code: NoSuchAttribute, matcheddn: "", message: "Unsupported user attribute: 1.1", referral: [] })
```

I'm not sure how to solve this issue, what's wrong with my filter ?

**Comment by nitnelave** [comment]
I think you might have an extra "&" in your filter. The syntax for a and b
and c is: (&(a)(b)(c)).

If that doesn't work, post the LLDAP logs with verbose enabled.

**Comment by Cyrix126** [comment]
Tried with (&(uid=${admin})(objectClass=people)) but same error from ldap (-7, Bad search filter).
the log:
https://share.libre-depanne.fr/selif/nginxlogdebugldap.txt

> Also, for the second query, it seems that you're somehow querying the "1.1" attribute for users, do you know why?

I have no clue. The only suspect would be the "HTTP/1.1 401 Unauthorized" with 1.1 ?

**Comment by nitnelave** [comment]
That's the nginx logs, can I get the LLDAP ones?

As for the 1.1, it's a special LDAP attribute meaning "don't return
attributes". It's not supported yet, but it's easy to do.

**Comment by Cyrix126** [comment]
https://share.libre-depanne.fr/selif/lldaplogdebug.txt
Le 26/02/2022 à 20:16, nitnelave a écrit :
> That's the nginx logs, can I get the LLDAP ones?
> 
> As for the 1.1, it's a special LDAP attribute meaning "don't return
> attributes". It's not supported yet, but it's easy to do.
>

**Comment by nitnelave** [comment]
Sorry for the delay, I didn't do much on LLDAP the past month. With #138 it should work for the 1.1 attribute.

From the nginx logs, I see that your search query is `(&(objectClass=*)((&(uid=${admin})(objectClass=people))=test))`.
I think you want something simpler, like: `(&(objectClass=*)(uid=${admin})(objectClass=person))` (I'm not sure what the `=test` is).

Can you paste your nginx config (the relevant parts) so I can help you configure it?

**Comment by nitnelave** [comment]
Hey @Cyrix126 did you manage to make nginx work? Can you share your config?

**Comment by nitnelave** [comment]
> I was on commit [2197fe7](https://github.com/nitnelave/lldap/commit/2197fe77a5d96213e47e4cbfa43d4720ab7d2241)

One commit too old :)

**Comment by nitnelave** [comment]
Ah yeah, but that you can just remove from the config. I'm not sure what the syntax of that URL is, but you want to request the uid of the user.

**Comment by nitnelave** [comment]
Aha, according to https://docs.oracle.com/cd/E19396-01/817-7616/ldurl.html:

>  LDAP URLs have the following syntax:
> `ldap[s]://hostname:port/base_dn?attributes?scope?filter `

So you want:
`url ldap://localhost:389/dc=domain,dc=com?uid?sub?(objectClass=person);`

or
`url ldap://localhost:389/ou=people,dc=domain,dc=com?uid?sub?(objectClass=person);`

**Comment by Cyrix126** [comment]
> or `url ldap://localhost:389/ou=people,dc=domain,dc=com?uid?sub?(objectClass=person);`

That's the one.
It works now, I will prepare the example config soon enough.
