### ISSUE TITLE
uid search is case sensitive

### ISSUE THREAD

**Issue by crobibero** [nitnelave/lldap#125]
All fields are currently case sensitive, where they should be case insensitive. The password field is expected to be case sensitive.

RFC (uid deep link): https://datatracker.ietf.org/doc/html/rfc4519#section-2.39

```
      ( 0.9.2342.19200300.100.1.1 NAME 'uid'
         EQUALITY caseIgnoreMatch
         SUBSTR caseIgnoreSubstringsMatch
         SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
```

**Comment by nitnelave** [comment]
At the risk of slightly breaking from the RFC, I'd like to keep most of the fields case sensitive apart from the username. The others are only used for display anyway.

**Comment by crobibero** [comment]
That works for me, thanks!

**Comment by nitnelave** [comment]
Alright, great! One small note: if you have users that have already signed up with uppercase logins, you'll need to lowercase them in the DB:

```sql
UPDATE users SET user_id = LOWER(user_id);
```
