### ISSUE TITLE
Jellyfin LDAP plugin guide

### ISSUE THREAD

**Issue by matthewstrasiotto** [nitnelave/lldap#134]
In order to use jellyfin with lldap, you'll want to do the following:

LDAP Bind User: 
```
cn=admin,ou=people,dc=example,dc=com
```

LDAP Base DN for searches: 
```
ou=people,dc=example,dc=com
```

User Filter:
```
(memberof=cn=media,ou=groups,dc=example,dc=com)
```
Admin Filter:
```
(memberof=cn=media_admin,ou=groups,dc=example,dc=com)
```

**Comment by nitnelave** [comment]
Thanks!

**Comment by h-2** [comment]
Giving the admin user as bind-user means giving the Jellyfin-instance admin access to LLDAP.

Can I create a user account with fewer privileges for this purpose?

**Comment by nitnelave** [comment]
Of course! You can create any user and add it to the lldap_strict_readonly group, and that should be enough. If you want to be able to reset passwords through Jellyfin (I believe it supports that) then you'll need the lldap_password_manager group instead.

**Comment by h-2** [comment]
Great, thanks for the quick reply! Might be worth adding to the tutorial for other newbies like me?

**Comment by nitnelave** [comment]
Which tutorial are you talking about? The Jellyfin one? Sure, you can make a PR for that.

Note that these roles and their use are described in the readme, in the "client configuration > general configuration guide" section.
