### ISSUE TITLE
Unable to authenticate against lldap from IPMI Controller

### ISSUE THREAD

**Issue by Leppunen** [nitnelave/lldap#139]
I'm trying to make my home server's IPMI controller to authenticate against lldap, where the ldap group 'admin' is mapped to the IPMI administrator group, and noticed that lldap cannot handle the search filter used by the IPMI. lldap debug log is below.

```

DEBUG lldap::infra::ldap_server: Received LDAP message: LdapMsg { msgid: 1, op: BindRequest(LdapBindRequest { dn: "cn=xx,ou=people,dc=xx,dc=xx", cred: Simple("********") }), ctrl: [] }

DEBUG lldap::infra::ldap_handler: Received bind request for "cn=xx,ou=people,dc=xx,dc=xx"

DEBUG lldap::infra::ldap_server: Replying with LDAP op: BindResponse(LdapBindResponse { res: LdapResult { code: Success, matcheddn: "", message: "", referral: [] }, saslcreds: None })

DEBUG lldap::infra::ldap_server: Received LDAP message: LdapMsg { msgid: 2, op: UnbindRequest, ctrl: [] }

DEBUG lldap::infra::ldap_server: Received LDAP message: LdapMsg { msgid: 3, op: SearchRequest(LdapSearchRequest { base: "ou=groups,dc=xx,dc=xx", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: And([Equality("objectClass", "groupOfNames"), Equality("cn", "admin")]), attrs: ["member"] }), ctrl: [] }

DEBUG lldap::infra::ldap_handler: Received search request: LdapSearchRequest { base: "ou=groups,dc=xx,dc=xx", scope: Subtree, aliases: Never, sizelimit: 0, timelimit: 0, typesonly: false, filter: And([Equality("objectClass", "groupOfNames"), Equality("cn", "admin")]), attrs: ["member"] }

DEBUG lldap::infra::ldap_server: Replying with LDAP op: SearchResultDone(LdapResult { code: UnwillingToPerform, matcheddn: "", message: "Unsupported group filter: Unknown field: objectClass", referral: [] })
```

**Comment by nitnelave** [comment]
It seems that it's trying to get "groupOfNames", but the LLDAP groups are "groupOfUniqueNames". Is that something that you can configure? Otherwise I can adapt the filters to match. I'll definitely improve the error message, it should be a valid filter that returns nothing (since the condition is valid but does not match anything).

**Comment by Leppunen** [comment]
I have no configurability for that behaviour. i can only specify most basic things like locations of groups/users etc.

**Comment by nitnelave** [comment]
Well, technically it's an issue with IPMI, but I'm willing to be a bit more flexible and allow the groups to also be listed as groupOfNames.

**Comment by Leppunen** [comment]
I tested this change and it looks like i can successfully authenticate against lldap now. Many thanks! 👍
