### ISSUE TITLE
add section to you description page

### ISSUE THREAD

**Issue by Abraka** [nitnelave/lldap#148]
Suggestion:
You should add section to you description page(somewhere on top) here, named "LLDP is compatible with following apps":
- Airsonic
- iDrac
- Emby
... with link to specific configuration, if there si something special to configure. You already have that in some way, but this need to be much more on eyes for users. 

Second...is LLDP compatible with SOGO and onlyoffice?

**Comment by nitnelave** [comment]
I'm not sure I implement any of these completely: the basic specification,
for instance, has support for modify operations, which is not supported in
LLDAP, we only have read-only (except for passwords).
But most apps that need to read from LDAP as an authentication provider
should work, and you can file a bug if they don't!

**Comment by Abraka** [comment]
Well, anyway..I still thing, that the list would be greatly helpfull for users, so they know if lldap is something they can use.

**Comment by nitnelave** [comment]
I added a section about which services are compatible or not to the README. In short: they _should_ all be compatible. Most likely they're not _all_ compatible (e.g. Nextcloud still has some issues) but in this case that's a bug that I'm willing to work on. However, I haven't (and can't) tested everything, so it's up to you to give it a try and see if there's an issue. Feel free to contribute any configuration that you made work, to save other people some troubles!
