### ISSUE TITLE
Documentation - Keycloak docs give incorrect bind dn

### ISSUE THREAD

**Issue by matthewstrasiotto** [nitnelave/lldap#156]
https://github.com/nitnelave/lldap/blob/4f89b73fe54a15c2ed60be49b7b31099c6f133c4/example_configs/keycloak.md?plain=1#L28

This doesnt allow me to import users into ldap, 

I believe the correct setting is:
```
cn=admin,ou=people,dc=example,dc=com
```

**Comment by nitnelave** [comment]
Are you sure you have the very latest LLDAP? The support for logging in
with uid= was added very recently.

**Comment by matthewstrasiotto** [comment]
uh maybe, i think that keycloak might have been the problem

**Comment by nitnelave** [comment]
I think it shouldn't be a problem now. Maybe fixed by #166 ?
