### ISSUE TITLE
Use sets for request attribute lists, ignore order when checkign attribute list equality in tests

### ISSUE THREAD

**Issue by matthewstrasiotto** [nitnelave/lldap#168]
Use sets for request attribute lists, 

- [ ] Refactor request structure to use sets internally
- [ ] Refactor test cases to ignore order when comparing attribute lists

_Originally posted by @matthewstrasiotto in https://github.com/nitnelave/lldap/issues/164#issuecomment-1120211031_

**Comment by nitnelave** [comment]
Fixed in https://github.com/nitnelave/lldap/pull/205
