### ISSUE TITLE
readme refers to LLDAP_USER_PASS_FILE while template toml refers to LLDAP_LDAP_USER_PASS_FILE

### ISSUE THREAD

**Issue by mmguero** [nitnelave/lldap#169]
In the readme it describes the admin user pass file environment variable as `LLDAP_USER_PASS_FILE`, but the template file lldap_config.docker_template.toml calls it `LLDAP_LDAP_USER_PASS_FILE`, which seems to be the correct name.

**Comment by nitnelave** [comment]
Thanks!
