### ISSUE TITLE
Add support for the `JpegPhoto` attribute

### ISSUE THREAD

**Issue by imsofi** [nitnelave/lldap#171]
This is a issue asking for the inclusion of the [JpegPhoto](https://ldapwiki.com/wiki/JpegPhoto) attribute from the [InetOrgPerson](https://ldapwiki.com/wiki/InetOrgPerson) class.

This adds a nice quality of life experience to help manage and centralize the profile pictures for the users under lldap. 

One example of a service using `JpegPhoto` would be Nextcloud and its `user_ldap_auth` module: https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html#nextcloud-avatar-integration

**Comment by nitnelave** [comment]
This shouldn't be too hard since I planned ahead and allocated an "Avatar" column in the users table. It needs a bit of massaging to get it exposed to the LDAP interface though.

**Comment by nitnelave** [comment]
I have a PR that mostly solves the issue: users can add their own avatar, and it's served as `jpegPhoto` in LDAP.

However, note that adding support to the migration tool is blocked by https://github.com/inejge/ldap3/issues/86.

**Comment by nitnelave** [comment]
@imsofi Do you think you could test the PR #284  ?

**Comment by imsofi** [comment]
Sadly i do not use lldap for my services anymore as i migrated to openldap completely. I may still see if i can test it in a container environment. But i will not be able to test how it integrates into things like nextcloud I am afraid.

**Comment by nitnelave** [comment]
If your openldap setup is similar to lldap (single ou=people with all users, single ou=groups with all groups) then it should be fairly simple to import the data into lldap, with the migration tool (apart from the passwords). But I understand if you don't want to get into that.

**Comment by imsofi** [comment]
Yeah, sadly my switch to openldap was to gain more flexibility with user creation and acl. So it is no longer easy to migrate back into lldap or another similar solution.

**Comment by nitnelave** [comment]
Marking as done, we'll see if any issue crops up.
