### ISSUE TITLE
Support for the userPrincipalName attribute

### ISSUE THREAD

**Issue by publicdesert** [nitnelave/lldap#191]
First of all, I really appreciate this project.

In my pull request (#190) I added an example configuration for Seafile. Since Seafile requires an unique identifier in an email-like format, I used the `mail` attribute in my config. I noticed however, that this is not really ideal, since the user is able to change his personal email address himself. Therefore I was wondering if it would be possible to add support for the [userPrincipalName](https://ldapwiki.com/wiki/UserPrincipalName) which would return `<name>@<tree name>`.

**Comment by nitnelave** [comment]
Is it really that bad to log in with your email address? They're still required to be unique so there won't be a conflict.

Adding support for that attribute would complicate things more than I'd like, when we have a perfectly good solution already.

**Comment by publicdesert** [comment]
The problem is that Seafile will treat you as an entirely new user if you change your email address through LLDAP.

For my personal setup I ended up using Authelia with LLDAP as the backend for Seafile and a few services that only support OAuth. Seafile's OAuth login feature is a lot more flexible then it's LDAP one. Thus I personally do not need this feature anymore, but it may be useful for others.

**Comment by nitnelave** [comment]
Yeah, for me that's more of a Seafile problem than LLDAP.

Glad you found a solution, I'll close this issue.
