### ISSUE TITLE
Alternatives to using Admin for LDAP Check

### ISSUE THREAD

**Issue by clbx** [nitnelave/lldap#196]
In all of the examples, and as far as I can tell, the Bind User always had to be admin. This is inherently insecure since the only user that applications can use has full access to the server. Adding a read_only group and/or adding the option for anonymous reads, would solve this issue.

**Comment by martadinata666** [comment]
Technically, afaik by default we already had `lldap_readonly` group, we only need to create a user and add it to readonly group, or maybe another suggestion lldap can create one readonly user by default.

And about the example, is about some familiarity and use lldap as easy as possible. Maybe we should create a doc about this security concerns like `yes you can use admin, but use readonly user with some tutorial create user with lldap_readonly`

**Comment by nitnelave** [comment]
Indeed this can be achieved by creating a user, member of the lldap_readonly group. It hasn't been properly documented though, so if anyone of you wants to add something to the docs and link it from the readme, that would be welcome!
