### ISSUE TITLE
Possible issue in Dockerfile

### ISSUE THREAD

**Issue by maestro-pkt** [nitnelave/lldap#22]
When I try to start the newest docker image, I'm receiving the following error:

```
error: Found argument '--config_file' which wasn't expected, or isn't valid in this context
```

It appears that /app/lldap is expecting config [DASH] file and it is being passed config [UNDERSCORE] file.  Should the CMD line in the Dockerfile be config [dash] file?

**Comment by nitnelave** [comment]
Indeed it should! I'm impressed that someone is actually trying to use the docker image already, it's not ready for use yet :)

**Comment by nitnelave** [comment]
Fixed and updated the docker image.

**Comment by adepssimius** [comment]
Hey, sorry I just submitted the same issue as it appears that the current docker image is not built with the fixed dockerfile.
