### ISSUE TITLE
Cannot install with docker

### ISSUE THREAD

**Issue by Pablohn26** [nitnelave/lldap#238]
When I am trying to install with docker I get the following error:

```
~/test/lldap$ sudo docker-compose up
[+] Running 1/0
 ⠿ Container lldap-lldap-1  Created                                                                                                                                                                   0.0s
Attaching to lldap-lldap-1
lldap-lldap-1  | [entrypoint] The /data folder doesn't exist or cannot be written to. Make sure to mount
lldap-lldap-1  |   a volume or folder to /data to persist data across restarts, and that the current user can
lldap-lldap-1  |   write to it.
lldap-lldap-1 exited with code 1

```

my main folder contains the following folder and files:

```
~/test/lldap$ tree 
.
├── docker-compose.yml
└── lldap_data
    └── lldap_config.toml

```

and I have tried using a volume (`            - "lldap_data:/data"`) and using a local folder (`      - "./lldap_data:/data"
`)

## Environment

OS: Ubuntu 20.04.4 LTS
Docker Compose version v2.6.1

**Comment by Pablohn26** [comment]
I make it work using a local folder and running 

> sudo chmod 777 lldap_data/

Maybe there is a permission problem when running docker-compose using `sudo`. 

How could we make it work using a volume?

**Comment by nitnelave** [comment]
I think that should help: https://serverfault.com/questions/984578/change-permissions-for-named-volumes-in-docker

**Comment by nitnelave** [comment]
Did that work for you?

**Comment by philskents** [comment]
I am getting the same issue with no sudo

**Comment by nitnelave** [comment]
Any news here?

**Comment by Pablohn26** [comment]
> I think that should help: https://serverfault.com/questions/984578/change-permissions-for-named-volumes-in-docker

I would go with option 1 if possible, rather than launching commands to fix permissions.

@philskents did your fix work?

**Comment by martadinata666** [comment]
Start from scratch should fix this, as the build already fix volume permission, and set `/data` path correctly. If there volume left kindly remove it first then recreate the container.

**Comment by nitnelave** [comment]
I think the issue was solved.
