### ISSUE TITLE
"Invalid username or password"

### ISSUE THREAD

**Issue by Kuuchuu** [nitnelave/lldap#24]
No matter what I try I'm unable to log in. Currently using the docker image, but I had the same issue when I set it up without docker before there was an image for it. It's running behind a reverse proxy, swag to be specific. Web page loads up no issue. I put in the username/password I set up but it says invalid. I've tried all sorts of combinations of things. I set the password/username in the toml file and in env variables, and tried not changing the username from "admin". No luck. Tried setting the password to something simple just in case it didn't like one of my characters, no change. I tried both binding the data directory to a folder and letting docker create a volume for it. Any help and/or guidance would be greatly appreciated, thanks!

**Comment by nitnelave** [comment]
Hey! Thanks for using LLDAP :) Just a quick disclaimer, it's not ready to use yet, it's missing core functionality. But it should work enough to log in as admin, though.

Just to be sure, with the default config, and the given values:
```
ldap_user_dn = "admin"
ldap_user_pass = "12345"
```

you can't login with the login/pass "admin"/"12345"?

If so, please try this:
- Press F12 to open the diagnostics tab.
- Refresh the page.
- Try to login.
- Paste here any output from the "Console" tab, and a screenshot from the "Network" tab.

**Comment by nitnelave** [comment]
After some investigation, I found a recently introduced error in the initial setup: we never set the admin password! That explains the issue. Fixed by #26.
