### ISSUE TITLE
Attach artifacts to release for popular architectures 

### ISSUE THREAD

**Issue by onedr0p** [nitnelave/lldap#242]
It would be nice if you could attach the binary for lldap to the releases page for popular architectures and platforms like gnu, musl, amd64 and arm64.

This could be done with https://github.com/rust-build/rust-build.action perhaps?

You also might be able to look at vector for github workflows that compile rust across architectures:

https://github.com/vectordotdev/vector/releases/tag/v0.23.0

**Comment by nitnelave** [comment]
Updated release v0.4.1 to include some artifacts: https://github.com/nitnelave/lldap/releases/tag/v0.4.1

If someone wants to contribute a github workflow that does it automatically for releases, it'd be welcome. Maybe whenever a tag is pushed, it creates a release draft with the artifacts (and then I can come and fix the changelog).
