### ISSUE TITLE
LLDAP_LDAP_USER_PASS_FILE does not work

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [nitnelave/lldap#263]
Starting like this:
```
col@col-laptop-asus ~/D/lldap (main)> echo -n "asdfasdfasdf" > admin_password
col@col-laptop-asus ~/D/lldap (main)> env LLDAP_LDAP_USER_PASS_FILE="./admin_password" cargo run -- run --config-file ./config.toml
```

Trying to log in with username "admin" password "asdfasdfasdf" results in an "Invalid username or password" message.

I've removed the databases for the test - there are no existing users.

**Comment by ColonelThirtyTwo** [comment]
Apparently the `*_FILE` vars are only read by `docker-entrypoint.sh, not by the main binary, so you can't use them if you're not using docker. Not very obvious.

**Comment by nitnelave** [comment]
Created https://github.com/SergioBenitez/Figment/issues/51 to see if we can handle them at config loading time instead.

**Comment by nitnelave** [comment]
I created the crate https://crates.io/crates/figment_file_provider_adapter to allow this pattern.
