### ISSUE TITLE
Improve page loading experence

### ISSUE THREAD

**Issue by jim-kirisame** [nitnelave/lldap#265]
Hi, currently the page is blank while loading the huge wasm, which is annoying when in slow network connection.

Add some loading animation will be better, or could you optimize the size of the wasm?

**Comment by nitnelave** [comment]
Reference: https://rustwasm.github.io/docs/book/reference/code-size.html#optimizing-builds-for-code-size

**Comment by nitnelave** [comment]
It would also be nice to get rid of rollup and replace it with a non-npm dependency, ideally in Rust.

**Comment by nitnelave** [comment]
I also investigated wasm-opt, but it doesn't help at all (actually makes the gzipped version slightly bigger).
