### ISSUE TITLE
Standardise the images

### ISSUE THREAD

**Issue by grehund** [nitnelave/lldap#268]
Is there a plan to standardize the images so we don't have a user field of `cn` in `:latest` and `uid` in `:stable`?
My understanding is that `uid` is the desired field long-term.

**Comment by nitnelave** [comment]
Are you sure you have the latest `:latest`, did you pull again? `uid` had been a user field for quite some time now.

**Comment by grehund** [comment]
if I tell Nextcloud LDAP to use `uid` it (Nextcloud) constantly logs errors. if I tell it `cn` = no errors. I'm frustrated that everything i read seems to contradict the last thing I read and the biggest doubt I have always seems to come back to LLDAP. I now have a problem with Authelia authenticating against LLDAP.

**Comment by nitnelave** [comment]
Sorry to come back to the charge, but `:latest` has had `uid` for strictly longer than `:stable` :)
The only possibility is if you didn't pull `:latest` again.

I'm closing this issue, feel free to create a new one with other problems that you find.
