### ISSUE TITLE
Import Lldap Accounts to Apple Contacts

### ISSUE THREAD

**Issue by CKranebitter** [nitnelave/lldap#274]
Thanks for the great tool.
I'm struggling with the above.
Just wondering - Is it even possible to set up an Ldap-Account in Apple-Contacts and synchronise it with the user-data from Lldap?

Thanks for helping.

**Comment by nitnelave** [comment]
Two way synchronization is not going to be supported, LLDAP is read-only with the LDAP protocol.
Maybe there's a way to import contacts from an LDAP server, but I don't know. If there is, it should work automatically with LLDAP.

**Comment by CKranebitter** [comment]
Apple needs the contacts to be in LDAP Data Interchange Format („.ldif“).
Does LLDAP support this?

**Comment by nitnelave** [comment]
No, we don't store data in this format. Though I think you could try to
query LLDAP with standard LDAP tools like ldapsearch and save the results
in ldif files.
