### ISSUE TITLE
Add support for PosixAccount

### ISSUE THREAD

**Issue by Zerwin** [nitnelave/lldap#285]
Would it be possible to add the necessary fields to support the [PosixAccount](https://ldapwiki.com/wiki/PosixAccount) Type ?
Currently already implemented fields that would be required for this are [cn](https://ldapwiki.com/wiki/Cn) and [uid](https://ldapwiki.com/wiki/Uid) while [uidNumber](https://ldapwiki.com/wiki/UidNumber), [gidNumber](https://ldapwiki.com/wiki/GidNumber) and [homeDirectory](https://ldapwiki.com/wiki/HomeDirectory) are missing.
There is also the optional fields [loginShell](https://ldapwiki.com/wiki/LoginShell), [gecos](https://ldapwiki.com/wiki/Gecos), [description](https://ldapwiki.com/wiki/Description), [authPassword](https://ldapwiki.com/wiki/AuthPassword) but I think these are for now not so important.

The reason I ask for support of this is that this would enable using LLDAP for logging into Linux Machines via nslcd. This is one of my prime use-cases for LDAP and something I would hope to see implemented in this project. 
(Side Note: I love the project, setting things up was about 20x times less work than with OpenLDAP, even for LDAPS. Thanks for the great work)

I hope this isn't deemed out of scope for this project, I would love to have basically all my use cases covered by LLDAP.

**Comment by nitnelave** [comment]
Hi! I think I'll solve this as part of https://github.com/nitnelave/lldap/issues/67 : you'll be able to have all the fields you want :)
