### ISSUE TITLE
Letsencrypt Support

### ISSUE THREAD

**Issue by zicklag** [nitnelave/lldap#292]
I need the ability to automatically create and renew LDAPS certificates with LetsEncrypt, and I might be willing to develop a pull request. Is this something you would be open to?

**Edit:** It might be easier for me just to integrate `acme.sh` into the container instead of building it into service itself. That wouldn't be preferable for users in general, though, so we wouldn't want to implement it like that in this repo probably.

I'm kind of in a hurry to get something working, so I might try that in a separate repo instead of a PR to the core.

**Comment by nitnelave** [comment]
Hmm, yes, it seems like you could automate it outside of the container based on cron and `acme.sh`, and just mount the certificates into the container. I don't think it belongs in LLDAP.

**Comment by KetchupBomb** [comment]
> ... and just mount the certificates into the container. ...

@nitnelave, this is the closest topical match I've seen so please pardon the old reply. Assuming the certificate & key are mounted in as Docker volumes from ACME to LLDAP, does LLDAP reload the certificate when ACME rotates them? Or would this require an LLDAP config reload? 

If a config reload is required, does LLDAP support some form of signal (`SIGHUP`?) to do so? 

I couldn't find the answer stumbling around the source code as I'm very unfamiliar with Rust. Thanks for any info.

**Comment by nitnelave** [comment]
No, there's no form of certificate reloading implemented, you'd have to restart the server.

**Comment by KetchupBomb** [comment]
Thanks @nitnelave. 

For those interested, if you, too, want to reload LLDAP when ACME rotates the certificate, one option is [Ofelia](https://github.com/mcuadros/ofelia)'s [`job-run`](https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md#job-run) execution type. You can spawn an instance of the `docker` image and [`docker restart lldap`](https://github.com/mcuadros/ofelia/issues/280#issuecomment-2561863012). A blind restart `@weekly` seems to be sufficient.
