### ISSUE TITLE
Build Script Fails

### ISSUE THREAD

**Issue by anomalyze** [nitnelave/lldap#3]
## Expected Behavior
Build script completes without errors.

## Actual Behavior
Build fails. I suspect this is because i do not have npm in my path or something.

```
$ ./app/build.sh 
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.05s
:-) [WARN]: origin crate has no README
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 9.53s
[INFO]: :-) Your wasm pkg is ready to publish at /home/jermz/projects/lldap-original/app/pkg.
./app/build.sh: 5: rollup: not found
```

## Steps to Reproduce the Problem

  1. Start up a new linux VM
  2. Clone Repo
  3. cd into directory
  4. Install Rust
  5. Follow instructions on README.md
  

## Specifications

  - Version: N/A
  - Platform: Linux   ##(amd64)
  - Subsystem: Debian Sid

**Comment by nitnelave** [comment]
Hey! The README contains a part about contributing, and more specifically about setup and dependencies: https://github.com/nitnelave/lldap#setup. Would you say that's enough?

**Comment by nitnelave** [comment]
Fixed by https://github.com/nitnelave/lldap/commit/0d8e3174905a78759e373f643cfb017091d3aff0
