### ISSUE TITLE
Web asset fail load when offline

### ISSUE THREAD

**Issue by martadinata666** [nitnelave/lldap#310]
As the title said, when the host gone offline and there is no cached `static fonts` and `bootstrap` the web management wont show anything (blank page). Use local defined bootstrap and fonts, so it doesn't need to fetch anything online.

Edit: i saw the Dockerfile that it download the fonts but somehow it doesnt exist

**Comment by martadinata666** [comment]
The assets downloaded but not used?

https://github.com/nitnelave/lldap/blob/5402aa5aa294a67ac0199c8dae5c4cbe27ca8f0a/app/index.html

Seems fetching over internet instead using local  ?

**Comment by nitnelave** [comment]
There's `index_local.html` for that: https://github.com/nitnelave/lldap/blob/5402aa5aa294a67ac0199c8dae5c4cbe27ca8f0a/app/index_local.html

You can see that it's copied correctly in the top-level Dockerfile: https://github.com/nitnelave/lldap/blob/main/Dockerfile#L48
but it's not the case for the automated images in CI. Would you mind updating them?

**Comment by martadinata666** [comment]
for a long time just realized there is two `index.html`, i will add it. 👍🏼

**Comment by martadinata666** [comment]
Closed by PR https://github.com/nitnelave/lldap/pull/311
