### ISSUE TITLE
Feature request: Healthcheck

### ISSUE THREAD

**Issue by kaysond** [nitnelave/lldap#312]
It would be great if the Dockerfile included a [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck). It should probably check both the ldap port and the web ui port. Web UI could be checked with `wget --spider` (included by default on the alpine builds, but debian seems to not have it).

For the ldap port, though, it seems a bit more complicated. From what I can tell debian has `ldap-client` via the `ldap-utils` package, but alpine does not.

Maybe the best way to do this is to write a custom healthcheck binary that checks both the web url and also does an ldap query?

**Comment by nitnelave** [comment]
The main non-trivial issue I see here is how to get the right port for the web/ldap/ldaps endpoints.

The easiest way is probably to either:
- Extract the configuration into a separate crate, and create a new binary that loads the config the same way.
  - Probably cleaner, and lets the compiler parallelize and cache better. This would probably come as part of a bigger crate-splitting effort.
- Extend the main binary to add a new subcommand that will run the healthcheck.
  - This will make the binary bigger than necessary, including potentially adding more dependencies (e.g. ldap client? though we can probably do without).
  - One possibility is to hide that behind a feature flag that gets built into the docker binary but not the command-line one?
  - Is it worth it? Is the binary size increase that big? Probably not, let's start simple.
