### ISSUE TITLE
[Feature] Add a Comment/Remarks/Description/Notes field to users/groups

### ISSUE THREAD

**Issue by Roemer** [nitnelave/lldap#328]
The idea is to have a text field to add information/notes to a user or group. This information is strictly visible and editable in the UI and is not exposed via LDAP.

**Comment by nitnelave** [comment]
That will get implemented as part of https://github.com/nitnelave/lldap/issues/67
You can create a field in the user/group schema and add whatever text you want to it. It'll be exposed via LDAP though.
