### ISSUE TITLE
Add vscode dev-container

### ISSUE THREAD

**Issue by Roemer** [nitnelave/lldap#331]
It would be much easier to contribute to the project if there is a VSCode Dev-Container definition in this project. This allows working on this project without installing any tools (beside vscode and docker).

**Comment by nitnelave** [comment]
I don't use VSCode myself. I'm open to contributions, it should be a fairly standard rust container with npm installed (for rollup).

You can actually use the Dockerfile at the top level as an inspiration, and you would even get the dependencies pre-compiled.
