### ISSUE TITLE
Static file backend

### ISSUE THREAD

**Issue by rlex** [nitnelave/lldap#339]
Hello! First of all, thanks for project.
I wonder if there is plans to implement file-based user DB? 
glauth (https://github.com/glauth/glauth) have nice example (but project looks pretty much abandoned): 

```
[backend]
  datastore = "config"
  baseDN = "dc=glauth,dc=com"
[[users]]
  name = "hackers"
  uidnumber = 5001
  primarygroup = 5501
  passsha256 = "6478579e37aff45f013e14eeb30b3cc56c72ccdc310123bcdf53e0333e3f416a"   # dogood
  sshkeys = [ "ssh-dss AAAAB3..." ]
[[users]]
  name = "uberhackers"
  uidnumber = 5006
  primarygroup = 5501
  passbcrypt = "243261243130244B62463462656F7265504F762E794F324957746D656541326B4B46596275674A79336A476845764B616D65446169784E41384F4432"   # dogood
[[groups]]
  name = "superheros"
  gidnumber = 5501
```

It can be useful on small install (labs, selfhosted stuff, etc). One idea is to run multiple pods in k8s reading from single configmap to achieve at least some level of HA without need for external DB.

**Comment by nitnelave** [comment]
I'm having trouble relating your requirements: small deploys, but HA?
If you want small-scale stuff, then (file-based) SQLite works very well.
If you really want HA then you could have a bunch of read-only mirrors of the SQLite file and it should work fine (special master for modifications, lots of read only slaves).
But then if you want HA it seems that having a simple postgres or even MySQL would be simpler, no? LLDAP itself is stateless so you can point many to the same DB.
If that's what you want, then there's an issue for supporting other DBs

**Comment by nitnelave** [comment]
(https://github.com/nitnelave/lldap/issues/87)
