### ISSUE TITLE
Support Synology

### ISSUE THREAD

**Issue by Roemer** [nitnelave/lldap#340]
I suppose many home users / home labbers have a Synology and want to use LLDAP for authentication.

Now Synologys LDAP implementation is a bit different. Here are a lot of information:
https://kb.synology.com/en-uk/DSM/help/DSM/AdminCenter/file_directory_service_join?version=7

I think there are two main things missing:
### Unique IDs (User ID and Group ID
This is not a very big deal, as Synology has a `HASH` method where pretty much any field can be converted to an int but maybe it is better if LLDAP provide such IDs.

### Crypted Passwords
Synology needs crypted Passwords from LLDAP according to RFC 2027 (see `userPassword` in https://www.ietf.org/rfc/rfc2307.txt)

**Comment by Roemer** [comment]
For the IDs, I see some possible ways:
1. Leave it as is and let Synology use `HASH` (however that makes sure they are unique)
2. Hash a field on our own and  return that
3. Add an auto-increment field to User and Group and just return that
4. Allow to manually specify the ids via UI with a simple check for uniqueness

**Comment by kesuskim** [comment]
Definitely look forward to it. What should possibly be done for it?

**Comment by nitnelave** [comment]
Before doing something like that, I'd like to have a confirmation from the synology devs that there's no way to make it work with the current system, i.e. no way to get synology to try to log in to the LDAP server every time, rather than store the hash themselves.

**Comment by Roemer** [comment]
I've opened a ticket for the Synology Support. Let's see what they answer.

**Comment by Roemer** [comment]
Ok I got the following response in the end:
```
In this case, the NAS will not be able to join the LDAP server since the "userPassword" field is indeed a requirement.
```

**Comment by nitnelave** [comment]
That complicates things...

I'd like to avoid complicating the whole password management aspect of the
project, especially if it's going to lower security. I don't want to hash
the password on the client side, and I don't want to send the password in
clear over http if we can avoid it. If Synology needs the user password
field, then I'll have to declare it incompatible with LLDAP.

**Comment by Roemer** [comment]
How about if we could enable this feature with an environment flag? So by default it would be as before but if someone really wants, he can enable that flag to get synology support on the cost of lower security.

**Comment by nitnelave** [comment]
The problem I have with this solution (I thought about it too) is that it
complicates the code a fair bit.

I don't know much about it, but is there a way to implement a Synology
plugin to provide LDAP authentication compatible with LLDAP?

**Comment by Roemer** [comment]
Hmm I haven't seen a package with a custom authentication mechanism for Synology yet. I have the feeling that this won't be possible.
