### ISSUE TITLE
Forgot Password feature request

### ISSUE THREAD

**Issue by zer0ish** [nitnelave/lldap#362]
Hello,

Would it be possible to add a Forgot password option that would use a 3or more question answer system?
This would be similar to the Freemium based windows tool "ADSelfService Plus"
For context it would work something like this:

1. Admin creates the account and provides the account info and PW reset page to change the default password. 
2. User has to go to the lldap site logging in with the admin set password.
3. Once logged in, user is asked to sets their 3 or more questions(based on a provided list) and answers. 
4. User is then prompted to set their new password.
5. If user forgets their password they must answer all the questions. Since this is a question based system I think forcing them to answer all of them instead of just one is better for security.

I have users who always forget their password and as an admin I don't like having to reset it every week.

**Comment by nitnelave** [comment]
There's a forgot password option with emails, that's easy to use, have you
tried that?

Security questions are in general terrible for security.

**Comment by zer0ish** [comment]
Sorry I think I just noticed the issue.
I'm just getting into Unraid to move away from my resource heavy windows servers and the unraid version of this is on LLDAP version 0.4.2-alpha

So I guess I the new version 3? has more options that I am not seeing in the unraid version. 
I believe it's someone else that put it on unraid. Wish that version would be updated.
I suppose this can be closed since even if you did add the request(whihc I agree email is better), it wouldn't be updated from the install I have in unraid.

**Comment by nitnelave** [comment]
The password reset function is much older, it was already in v0.1, and it
definitely is in the unraid version. Maybe you didn't set it up for sending
emails, though?

**Comment by zer0ish** [comment]
Here is a screen shot of the options I have in unraid to edit:
https://drive.google.com/file/d/1gauJ4bMy-TnQBkxT2w-FVvNURWs2oeW1/view?usp=share_link

And this is all I have for when I'm in the webgui:
https://drive.google.com/file/d/1wLK9yREALyw4g0xLZ-HpU2CcQtkADVJ4/view?usp=share_link

I'm new to unraid, but I really don't see any options for setting this up.

**Comment by martadinata666** [comment]
As the options doesn't show, then you need to manually modify the `config.toml`. Looking from the images you attached, the `config and it friends` path is on `/mnt/user/appdata/lldap/`

**Comment by zer0ish** [comment]
> As the options doesn't show, then you need to manually modify the `config.toml`. Looking from the images you attached, the `config and it friends` path is on `/mnt/user/appdata/lldap/`

Thanks for this.
I assumed setting this up was part of the GUI.
