### ISSUE TITLE
How to setup a connection?

### ISSUE THREAD

**Issue by SaschMie** [nitnelave/lldap#364]
hello all,

i have lldap installed on my unraid nas and i am currently trying to understand how an application can access it.

The dn is set to dc=example,dc=org.

Now I am trying to connect emby to it, however I am not clear what settings it needs now.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/101413773/199682932-e1fd5312-0fe3-4679-a478-dde487aab8ae.png">

The log of lldap shows me that the connection works.

```
2022-11-03T09:01:25.642002244+00:00 INFO     LDAP session [ 115µs | 61.14% / 100.00% ]
2022-11-03T09:01:25.648153101+00:00 INFO     ┕━ LDAP request [ 44.7µs | 38.86% ]
```

But i cant login with a tester user, emby claims all time that the credentials are wrong.

Maybe someone can help here?

**Comment by martadinata666** [comment]
https://github.com/nitnelave/lldap/blob/main/example_configs/emby.md

**Comment by nitnelave** [comment]
Have you had a look at the provided example_configs?

A little LDAP vocabulary: DN is distinguished name, the full identifier for
a user or group. The bind DN is the admin user name, and the credentials is
the password.

The user search base is where you have users stored, so "ou=people,
DC=example, DC=com".
The user filter is how to find a user trying to log in, so you can have
`(uid={0})` for the basic login, or you can make it so they can log in with
email as well, or restrict them to a specific group.

What application is that config for? Once you get it working, I'd
appreciate if you could contribute your configuration for the next person.

**Comment by SaschMie** [comment]
i tried it not this way (like the example):

![image](https://user-images.githubusercontent.com/101413773/199692537-8df40e8b-082c-4237-a2cd-cfc123b182c1.png)

but im not sure about that bind credentials field, what have to be there. Is that this JWT pw from docker or a pw from an admin user?

Because now i got this:
```
2022-11-03T09:54:56.560870520+00:00 ERROR       ┝━ 🚨 [error]:  | error: Authentication protocol error for `Protocol error: `This error results from an error during password verification``
2022-11-03T09:54:56.560879214+00:00 ERROR       ┕━ 🚨 [error]:  | error: Authentication error: ` for user 'admin'`
```

**Comment by martadinata666** [comment]
the sample config `changeme (replace with your password)`, so replace with your admin password.

**Comment by SaschMie** [comment]
Yes that was the problem :) now its working! Maybe it should be pointed out in the example that this admin / credentials are an admin of that ldap.

Thank you all :D
