### ISSUE TITLE
AWS S3 backend?

### ISSUE THREAD

**Issue by pwillis-eiq** [nitnelave/lldap#367]
I know the current backend is SQLite, and I'm sure that works okay for most folks, but it seems for the use case SQLite might not be necessary, or maybe could be augmented to provide some operational benefits.

I'd like to propose using AWS S3 as an alternative backend. It's a very different paradigm than using something like SQLite, but I think it would greatly reduce the complexity of running the software reliably.

To use SQLite as the backing store, there are a couple restrictions:

1. The backend is a file. Replicating files reliably is generally considered non-trivial, and so most people will not replicate the file. Therefore, only one process should be operating on this one file at any given time. Since the file isn't replicated and only one process can operate on it, you can only really run one process to serve the service. Therefore you can't do high-availability (or even load-balancing).

2. Since the backend is a file, there needs to be a backup process to preserve the file (unless you have disk snapshots, although those may not be safe without an exclusive lock on the database, and at that point you might as well just copy the file or run online backup commands and not do disk snapshots). Managing the backup process, verifying it works correctly, and restoring the backups at start up, are now an operational burden. It's not insanely difficult, but it's one more thing the person running the software has to think about, and it's error-prone.

3. Since the backend is a file, security (for the whole database) is limited to file-level security of a single file on a single file namespace.

To solve these problems, I propose a backend store of AWS S3.

1. Since the backend would be an object store, there is no limit to the number of instances of the server that can run at any given time. High-availability is trivially achieved simply by running multiple copies of the server.
   1. AWS S3 provides strong read-after-write consistency guarantees. Right after any instances writes data, any client that reads next will get the new data. If you prefer you can always have instances that keep a local cache for a short period, or you can have them fetch S3 for every call.
   2. For S3-compatible services with eventual consistency, writes can be done by a read-write-instance, while reads can be performed by a read-only-instance, similar to a traditional SQL database. (I'd have to confirm, but I think using the read-write-instance for reads would allow you to get queries that were just written, while some read-only-instances might lag depending on where they were reading from, but I actually don't know)

2. Since S3 object stores have high durability guarantees, there is less urgent need to backup the data. If data resiliency guarantees are warranted, a process out-of-band of the server can version or archive objects at any time, and manage them with a lifecycle policy. The management of "backups" then becomes a passive, trivial, virtually guaranteed process.

3. S3 object stores typically support ACLs which can tightly control data access.

Assuming all these points are valid, how would one implement the S3 backend?

Option 1. Use path prefixes to segregate records and types. This doesn't let you easily do queries like in SQLite, but if you're just looking up a single user's metadata by name, seems like it would work?

    S3-BUCKET/lldap/dc=com/dc=example/ou=people/cn=bob
    S3-BUCKET/lldap/dc=com/dc=example/ou=groups/cn=family

Option 2: Store an entire sqlite database(s) in S3. If each read and write copies the entire file to/from S3, it will be a bit slower, but you gain both the features of SQLite and the operational simplicity of S3, with less fine-grained control over the data in S3.

    S3-BUCKET/lldap/dc=com/dc=example/db.sqlite3

Option 3: ?

**Comment by wailashi** [comment]
You can use [Litestream](https://litestream.io/) to replicate SQLite to S3 among other locations.

**Comment by nitnelave** [comment]
I don't really plan on explicitly supporting AWS as a backend. The main target of this project is for self hosting, and I don't want to add the extra complexity.

However, to your concerns:
- high availability: support for other DBs is planned, so you could have MySQL/postgresql and several instances connected to it (the service itself is stateless). If you need load balancing though, you're probably using the wrong project :)
- backups: yes, that's part of the life of a self hoster. Backing up SQLite by copying the files without sync will get you all the data in 99% of the case, and lose a couple of transactions in the rest. There's also some dedicated SQLite solutions, you can get a docker Cron that will properly backup the DB. And finally, backing up a MySQL/postgresql DB (or having it replicated) is a well understood problem.
- regarding security, you can restrict the access to the file to a specific LLDAP account and grant ACLs separately to connect to that account. Again, the main purpose is a self hosted lab, I fail to see a use case where this is not sufficient.

And as @wailashi said, if you really want S3, you can use litestream.

**Comment by pwillis-eiq** [comment]
Unfortunately Litestream is intended that you only run one copy of your application, hence there is no high-availability or load balancing. A better choice would be [LiteFS](https://github.com/superfly/litefs), which is intended to replicate to multiple processes, which would provide HA and load balancing. This is probably good enough for most folks (although dependence on FUSE may not work for constrained systems and is not portable).

If you are planning to support other SQL DBs, I would still suggest that an I/O abstraction that supports non-SQL storage would provide a great deal of utility. As someone who also self-hosts apps, I would much rather avoid SQL's idiosyncrasies and operational model and use something simpler like S3. I think this will become more popular over time as people see how simpler designs can reap lots of benefits. (Of course some apps really need complex queries over gigantic relational datasets, and SQL DBs will remain best for that)

In terms of self-hosting, self-hosted S3 like [minio](https://github.com/minio/minio) and [Ceph](https://github.com/ceph/ceph) are (I think) easier to run and maintain than an SQL server, and are compatible with Hosted solutions should someone not want to think about backups, disk space, etc.

But in any case, @nitnelave I totally understand wanting to keep your project simple and that these are not part of your goals 👍  Thanks very much for your reply, and good luck with your project!
