### ISSUE TITLE
Strange formatting on password reset email link

### ISSUE THREAD

**Issue by iplusplus42** [nitnelave/lldap#370]
Hello! While testing my LLDAP configs, I found that the emailed password reset link isn't directly usable and appears to have been broken up by some kind of text wrapping. Below is the text from the email I received:

```
Hello Andy,
This email has been sent to you in order to validate your identity.
If you did not initiate the process your credentials might have been
compromised. You should reset your password and contact an administrator.

To reset your password please visit the following URL: http://lldap.exam=
ple.com/reset-password/step2/W11CIJ7nKr0LRp4UaYUgshRMf4RpsL5mzgLhJGIxyrCA=
P129DyO0HjMoxG5wj9wTuAZzSoxaSTIe2BvBw7FSCt7sYkcDDZRLGqlf

Please contact an administrator if you did not initiate the process.
```

I could have something misconfigured somewhere, but I'm not sure. I'm running LLDAP v0.4.2-alpha on the lldap:latest Docker image. Please let me know if you need more information. Thank you!

**Comment by nitnelave** [comment]
The domain part is taken from your configuration, the "http_url". Can you
double check it?

**Comment by iplusplus42** [comment]
`http_url = "https://ldap.example.com"`
That's what I have in my lldap_config.toml. It differs slightly from the link in my first comment, and that's because I noticed a few typos in the URL, but the issue still occurs. Thank you!

**Comment by nitnelave** [comment]
Okay, I went through the code, I don't see any way that it would create this message.

However, looking at the body of the email, I see that it's aligned at 80 columns: I suspect either your SMTP relay and/or your email client of wrapping the message and adding the "=" when splitting the URL. Can you try sending the message from a different account, to a different account, or reading it with a different email client?

**Comment by nitnelave** [comment]
Alright, this seems to be a case of [Quoted-printable encoding](https://en.wikipedia.org/wiki/Quoted-printable), where lines over 76 characters are escaped with an equal sign. It's a technically valid, if a bit old, encoding, that is usually supported by big clients.

**Comment by nitnelave** [comment]
Note for the future, or if someone wants to take this up: in mail.rs, instead of using `body`, we should use `singlepart`: https://docs.rs/lettre/0.10.0-alpha.1/lettre/message/index.html#single-part

**Comment by nitnelave** [comment]
The username can be UTF-8, so I'd like to have something that supports it.

Normally, lettre automatically chooses the appropriate encoding. I'm guessing here they went with QuotedPrintable for the long line, but even then, the client is supposed to support it correctly, that's a bog standard format.

I'm sorry for the users here, but it seems to be more of a SMTP server/email client problem than an LLDAP problem. Check with your email client whether they support the QuotedPrintable encoding, and if not, why not?

**Comment by codestation** [comment]
Same problem, the email is broken on RoundCube (Webmail app) and Gmail (Android App). Consider adding the `Content-Type` header.

**Comment by nitnelave** [comment]
Last time I tried, there was a problem with the library making it hard to
do this simple thing. I'll have another look when I have a minute.

**Comment by nitnelave** [comment]
Thanks @wkeiuluf , that really helped! Can someone confirm that it's working correctly with the latest image?

**Comment by iplusplus42** [comment]
I can confirm that the email is working correctly! Thank you to everyone involved!

**Comment by codestation** [comment]
Thank you. Can confirm is working with the email clients.
