### ISSUE TITLE
Is there any documents for get token for graphql programmatically?

### ISSUE THREAD

**Issue by leopku** [nitnelave/lldap#375]
I wanna write some app backend with lldap but troubled with how to get token to access graphql endpoint.

Any advice?

**Comment by nitnelave** [comment]
Hmm, the doc is definitely missing. Unless you're writing your app in Rust (in which case you can use the `lldap_auth` crate, and I might have to publish it), it's going to be hard to use the OPAQUE protocol to log in (not stabilized yet, and we use a somewhat old version).

Thankfully, there's a more classical way forward: You can send a json POST request to `/auth/simple/login` with `{"username": "john", "password": "1234"}` in the body.
In the response, you'll have 2 http-only cookies (the JWT and the refresh token, valid longer), and they will also be in the response. The JWT is valid for a day, but within 30 days you can just call `/auth/refresh` and the refresh cookie will be enough to identify you.

The JWT is then used for identifying other requests, either through a cookie or through a Bearer Authorization header.

**Comment by leopku** [comment]
@nitnelave You reply really help me. Thank a lot.

**Comment by nitnelave** [comment]
I'm looking forward to your app, I hope you'll share it!

If you want to write the authentication part in a doc somewhere, that would be helpful.

Also, BTW: I'm working on a somewhat big feature (https://github.com/nitnelave/lldap/issues/67) that'll change the API, including extending GraphQL. It'll be backwards-compatible, but you might be interested in supporting it once it's released (not quite for right now though).

**Comment by leopku** [comment]
My app not start yet.

I can write and share a small demo app for your advise.
