### ISSUE TITLE
[bug] passwords change after container deletion

### ISSUE THREAD

**Issue by LoricAndre** [nitnelave/lldap#397]
Hello,

Thank you for creating this service !
However, after setting it up, everything worked perfectly and I could add users and use them, until I ran `docker-compose down && docker-compose up -d`.
Then, after it gor back up, I was unable to login using the accounts until I manually changed the password to what I originally set them during the setup. The logs go in that direction, indicating that the admin password I am supplying is wrong until I manually set it back.

My setup is quite basic (no ssl, admin account is `root`) but inside a bigger array of docker-compose services, so I would like to avoid having to paste it here if possible.

I am running this on an arm64 machine if that is of any help, using docker `stable` tag.

**Comment by nitnelave** [comment]
Hmm, could you share the relevant docker-compose config? Namely:
- The LLDAP block, with any mount
- Any volume referenced by the LLDAP block

When you managed to reconnect after changing the password again, did you still have the new users you created? It sounds a bit like the DB was deleted when you ran `docker-compose down`.
Finally, can you post the beginning of the verbose LLDAP logs? I.e. config, startup messages, and one login attempt.
