### ISSUE TITLE
Doesn't start when data volume is on nfs

### ISSUE THREAD

**Issue by chrisb86** [nitnelave/lldap#398]
I recently moved my docker data to NFS shares.

I mount the nfs directory in my fstab and pointed the docker-compose.yml to the respective directory.

When trying to start lldap, it faisl with the following message:
 "Could not bring up the servers: while connecting to the DB: pool timed out while waiting for an open connection". 

When I move the volume back to local storage, everything works.

Any ideas?

**Comment by wailashi** [comment]
LLDAP uses SQLite which does not work well when the database file is on a NFS mount.
Support for other databases is tracked in #87.

**Comment by chrisb86** [comment]
Okay, thank you. I moved everything back for now and wait for the new backend possibilites.
