### ISSUE TITLE
Should this setting be "cn" instead of "displayName" - Authelia Config

### ISSUE THREAD

**Issue by lordratner** [nitnelave/lldap#399]
https://github.com/nitnelave/lldap/blob/c64d32e2c0cc698c61ca40e8364ab0cd7934cd46/example_configs/authelia_config.yml#L43

I could be looking at this wrong, but when I look at the full tree with ldap.exe, I don't even see a "displayName" attribute.

**Comment by nitnelave** [comment]
They're synonyms. In the update that's coming up to implement #67 , the aliases will be made more formal and exposed to LDAP as the structure. You can see here the translation of LDAP attribute name -> data: https://github.com/nitnelave/lldap/blob/main/server/src/domain/ldap/user.rs#L51
