### ISSUE TITLE
Support a simpler method of logging in and changing passwords

### ISSUE THREAD

**Issue by nitnelave** [nitnelave/lldap#42]
To facilitate other frontends, a classic login methods sending the password in clear to the server could be added. That should come with a stern warning about DDoS attacks since the server will be doing all the steps of the OPAQUE protocol.

**Comment by JaneJeon** [comment]
Or we could just support something like https://github.com/ltb-project/self-service-password? obviously that would require that lldap be "writable" from the perspective of that application

**Comment by nitnelave** [comment]
That's a different thing: what you're suggesting is a way for users to change their password and/or reset it via email. This is already supported by LLDAP with the web UI, and the LDAP interface also allows changing the password. LLDAP should _already_ be compatible with self-service-password, but it _shouldn't be needed_ because the functionality is already built-in.

This issue is about facilitating scripting, especially with other languages, to allow them to authenticate via simple login/password instead of going through opaque.
Note that it was implemented in https://github.com/nitnelave/lldap/pull/121, we should close this.
