### ISSUE TITLE
SMTP ENABLE_PASSWORD_RESET

### ISSUE THREAD

**Issue by zer0ish** [nitnelave/lldap#431]
I just changed my settings so that I can modify the SMTP info using the variable option in Unraid docker container instead of going to the config file.
I re-commented them in the config.
Set the variables in the container.
I wanted to test this variable to see if it works and noticed that if this one is set to False, the reset link still goes through.
Container Variable: LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET

Shouldn't this either remove the reset option from the GUI or have a error message and not send a reset link?

Also, is it needed to have the double underscores for these? The config file shows the example with double underscore. But wanted to make sure it wasn't a typo.

**Comment by nitnelave** [comment]
Hmm, it seems we don't _actually_ use that config value anywhere. We should probably add an endpoint on the server to check whether it's supported (like `/server_info` returning `{password_reset_supported: true}`), check that on page load in the client and change the UI in case it's not supported.

Good callout!

It shouldn't be too hard, if someone wants to pick this up.
