### ISSUE TITLE
extra colon in avatar/jpegphoto return

### ISSUE THREAD

**Issue by LiFiCode** [nitnelave/lldap#435]
the command

```
ldapsearch -H ldap://xxx -D 'uid=xxx,ou=people,dc=xxx,dc=xx' -LLL 'uid=xxx' uid cn sn displayname mail jpegphoto memberOf -o ldif-wrap=no -b 'ou=people,dc=xxx,dc=xx'  -w xxxxxx
```
returns

```
dn: uid=xxx,ou=people,dc=xxx,dc=xx
uid: xxx
cn: xxx
sn: xxx
displayname: xxx
mail: xxx
jpegphoto:: /xxx
```

as you can see - the jpegphoto has two colons "::"

**Comment by nitnelave** [comment]
That is the correct output for a base-64 encoded value, see `man ldif`: https://man7.org/linux/man-pages/man5/ldif.5.html

Note that this behavior is entirely within `ldapsearch`: LLDAP returns the value of the raw bytes, it's just `ldapsearch` that decides to convert it to base 64 for display.

(LLDAP does the same thing for the GraphQL API, but that's unrelated)

**Comment by LiFiCode** [comment]
thank you very much for your quick answer.
i spent hours finding the source of the missing avatars - oh well...
