### ISSUE TITLE
Authentik not syncing

### ISSUE THREAD

**Issue by theAlevan** [nitnelave/lldap#437]
I've been trying to get Authentik working with lldap, but it will not sync (my other apps, including a test Authelia instance works). 
My Authelia config:
-authentik user added to [lldap_password_manager] group
-as there are no official guides for lldap and Authelia, I combined the [official docs](https://goauthentik.io/integrations/sources/ldap/) with [sample configs](https://github.com/nitnelave/lldap/tree/main/example_configs) for supported clients.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/36887550/217902869-f73a8d48-afa9-40cb-93a4-ef27a14598cf.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/36887550/217903095-7a72b6c6-a20d-4b49-ab3c-6720394d30d4.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/36887550/217903177-445edaf0-2c4f-4172-b0b6-e83621c1f60d.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/36887550/217903294-e74222d4-0140-47bc-a0bb-14b20cf2681c.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/36887550/217903390-e62d96e4-644c-470e-9c2f-f3676cd5cfc9.png">

**Comment by theAlevan** [comment]
Found the issue, I had a user named test on both lldap and authelia. After I deleted the authentik test user, syncing began.

**Comment by arcoast** [comment]
@theAlevan Apologies for pinging you, but it appears I'm about three days behind you, just wanted to check if you managed to import your groups from lldap into Authentik, all my users are there but no group info with the same settings you have above.

**Comment by arcoast** [comment]
Not to worry, got it squared away now.
https://github.com/nitnelave/lldap/pull/444
