### ISSUE TITLE
Password visible during password reset on web interface

### ISSUE THREAD

**Issue by DarkSpir** [nitnelave/lldap#442]
I log into lldap via its webinterface on port 17170, click on the user logo on the top right, and select "Profile". Then I click the button "Change Password".

The first input form "Current password" is type="text", the second and third input forms "New password" and "Confirm password" are type="password". Thus the new passwords are hidden behind whatever char the OS uses for obfuscating password input boxes but the old password is visible in plain text. Not sure if that was desired behavior.

**Comment by DarkSpir** [comment]
I have no experience with programing in Rust but if I have to guess I'd say on /app/src/components/change_password.rs between line 248 and 249 a input_type="password" is missing. If that is not the desired behavior.

**Comment by nitnelave** [comment]
It sounds like you found the spot! Would you like to do a PR?

**Comment by DarkSpir** [comment]
Created PR #443

**Comment by DarkSpir** [comment]
Wow I think this was the first time I created a PR to actually change code of something that has not been written by myself. Thanks!
