### ISSUE TITLE
lldap hates me (or hates my name)

### ISSUE THREAD

**Issue by RoryNesbitt** [nitnelave/lldap#471]
So I don't really know how to debug this but I promise it's not a joke.

My name is Rory, quite a good name if I do say so myself. However lldap doesn't seem to think so. If I create a user with the uid rory I can't use it through authelia.

I'm running both lldap and authelia on unraid. My authelia config looks very much like the example in this repo, and I can log in to any of the lldap users I make, except if I call them rory. rory can however log in directly to lldap.

There is nothing in the logs, except a lack of logs. if I use a different user and a bad password I get an ERROR. But, If I use the rory user this error never appears, whether I use the correct password or the wrong one.

**Comment by martadinata666** [comment]
jokes aside, is another 4 chars name work fine? 🤔 roru tori tory, etc. As base config uid admin seems work for 5chars.

**Comment by RoryNesbitt** [comment]
I swear to you I tested the name test exactly for this reason. but now when I go to confirm it I get the same issue

**Comment by martadinata666** [comment]
> I swear to you I tested the name 'test' exactly for this reason. but now when I go to confirm it I get the same issue

how about the password? is it also 4 char? I think lldap looking for 8 char.

**Comment by RoryNesbitt** [comment]
Password is consistently 8 or more characters. lldap doesn't let you create the user with a shorter one

**Comment by RoryNesbitt** [comment]
this is honestly insane.
So just there after thinking it was the length I made a user 'tes', which worked fine. so I made the user 'roru', again fine.
So then I delete those and make 'rory' again with the same email as roru and the same password as roru and nothing else filled in. Doesn't work

**Comment by martadinata666** [comment]
set verbose true in config, and attach lldap log here. let's see what magical rory doing, pretty interesting. FYI I'm trying to replicate it but I can't, and I'm on stable 0.4.1. Dunno if that will make diff.

**Comment by RoryNesbitt** [comment]
[lldap.log](https://github.com/nitnelave/lldap/files/10948945/lldap.log)

So as I say, nothing pops up when I try to log in from authelia, but for this one what I done was 
- restart lldap
- create user rory
- try to log in from authelia
- log out user admin in lldap
- log in successfully from lldap
- try to log in from authelia again

**Comment by RoryNesbitt** [comment]
So uhm, authelia had blocked the rory user, and even when the user was deleted and recreated the block would persist. turns out this has nothing to do with lldap.

oops
