### ISSUE TITLE
How do I login?

### ISSUE THREAD

**Issue by benisai** [nitnelave/lldap#48]
I really want to use this, but how do I login to the interface? All I see is username and email

**Comment by nitnelave** [comment]
Hi!

During the initial run, the server creates an admin user using the username and password that you put in the configuration. When logging in as this user, you'll see the list of users on the server, which should be just the admin user. You can then create new users with the "create user" button.

Note that the frontend is not quite finished, you won't be able to create groups right now. If you don't need groups, all the basic functionality should be there.

**Comment by benisai** [comment]
I must have a bad build/image, I used latest tho. all I see is username and email prompt.

**Comment by benisai** [comment]
I can't ignore. It needs the @ symbol otherwise I cannot press login.

**Comment by benisai** [comment]
@nitnelave  the email field requires the @ symbol. This is a bug in the code / UI. Can you open a ticket for it?

**Comment by nitnelave** [comment]
Calm down, there's no need to send messages this close together, I'm working on this project in my free time.

I checked the code, and I checked all the history of the specific file, and there is and has never been a requirement for a "@" symbol.

However, there is a requirement for a minimum of 8 characters. Maybe that's what tripped you up?

**Comment by benisai** [comment]
@nitnelave  thank you. I will pull it today. My PW is probably not 8 char. Thank you for this project and your time.

**Comment by nitnelave** [comment]
Try to delete the users.db: since the admin user already exists, the password is not changed (i think). If you delete the DB, the user will get recreated with the right password.

**Comment by benisai** [comment]
I connected to the container and rm users.db, restarted the container, but still admin/password123 does not work. 
I even removed any/all volumes. 
Nothing I do will log me in. Just says invalid creds

**Comment by benisai** [comment]
Well, Let me ask you, how do you mount the config file? Can you share your method, so I can get this working. 🙂👍🏻
