### ISSUE TITLE
MySQL schema uses BLOB instead of LONGBLOB

### ISSUE THREAD

**Issue by pixelrazor** [nitnelave/lldap#486]
Discovered when testing #484. MySQL BLOB is limited to 64kb, which is far too small for avatar. It looks like [avatar is already configured properly](https://github.com/nitnelave/lldap/blob/b2cfc0ed03b41db25b49a03da31e57582c661c29/server/src/domain/model/users.rs#L59), but it that doesn't appear to be effecting the schema creation.

**Comment by pixelrazor** [comment]
Digging more i found that the issue is probable [here](https://github.com/nitnelave/lldap/blob/b2cfc0ed03b41db25b49a03da31e57582c661c29/server/src/domain/sql_migrations.rs#L105) where we create it without the binary size. Do we need to change that or the v2 migration to do the right type? or maybe add a v3 migration to upgrade that type?

**Comment by nitnelave** [comment]
We'll probably need to do a fancy dance like we do with display_name at the end of the migration file to move the columns around and change the type, using a v3 migration marker.
