### ISSUE TITLE
Allow setting environment variables for configuration

### ISSUE THREAD

**Issue by onedr0p** [nitnelave/lldap#502]
Hi 👋🏼 

I was wondering if it would possible if we could be able to set configuration for LLDAP via environment variables in additional to a configuration file? My thinking is that env would take precedence over the config file options. This is a very common pattern in software development, especially when applications are supported in containers.

The use-case here is that Kubernetes and containers in general have a much easier time configuring applications via env rather than a file that is only on disk. The current configuration file appears to be pretty flat with no nested config, so it shouldn't be too hard to implement... however I am not a rust developer so I am not sure if the current library being used exposes this as an option.

**Comment by nitnelave** [comment]
There are also examples of env variables set in the docker-compose.

**Comment by onedr0p** [comment]
I was looking over that config file for a bit and didn't even see that 🤦🏼 . Time to get coffee and actually wake up before Githubbing 😄

**Comment by onedr0p** [comment]
Would there be anyway to set the `key_file` to an actual passphrase instead of a file path? I would like to not write files to disk if it can be avoided.

**Comment by nitnelave** [comment]
Sure, you just remove the `_file` suffix.

**Comment by nitnelave** [comment]
But you can generate it once (just start the server once) and then have this file replicated in read-only to every instance.

**Comment by nitnelave** [comment]
It's not that simple to generate a key, it depends on, well a dependency (opaque in this case), it's fairly implementation-specific. I don't really want to factor this out for this specific use-case.

I think the workaround you mentioned is the easiest. Feel free to contribute/check out https://github.com/Evantage-WS/lldap-kubernetes.

**Comment by nitnelave** [comment]
Let's say that I added a command `lldap create_secret_key` that creates a file with the secret key, and you could set the key in env. How would that significantly change the setup you describe? AFAICT, it would only remove step 5, you'd still need to "start lldap" to generate the key and extract it.

Generating it with an outside program is more or less not possible.

**Comment by onedr0p** [comment]
Yeah I don't see that helping out much either.

I guess this is more or less turning into an architectural discussion on why lldap is creating that key for us rather than letting the user pre-configure it via env, surely it could be possible if it matches the correct syntax or cryptography?

If I understand correctly, in theory I could run lldap locally and have it spit out a key and use that in my kubernetes deployment in an env var if it was supported?

**Comment by nitnelave** [comment]
Alright, can you create an issue for that then? That way I can track it better.

**Comment by onedr0p** [comment]
> Alright, can you create an issue for that then? That way I can track it better.

Will do.

I also have a suspicion that if you force people to provide this value in env or the file config it would remove a lot of code since you do not need to worry about generating it. But maybe that's just wishful thinking :D
