### ISSUE TITLE
[BUG] No Emails Attempted To Be Sent

### ISSUE THREAD

**Issue by ghost** [nitnelave/lldap#743]
Preface: `example.com` is not the domain in use, of course. It's just used for redaction of information in this GitHub issue. Note also: I do not use Discord.

---

When clicking `Reset password` on `https://example.com/reset-password/step1`, no email is even attempted to be sent at all. The UI says `A reset token has been sent to your email.`, but no such thing happens nor is it even attempted.

This is the *only* thing that appears in verbose logs when trying this (note that `test` is the user):

```
2023-11-21T19:21:34.049506181+00:00  DEBUG    HTTP request [ 138µs | 100.00% ] method: "GET" | uri: "/auth/reset/step1/test"
2023-11-21T19:21:34.049629773+00:00  DEBUG    ┕━ 🐛 [debug]:  | status_code: 200
```

Docker image in use: `ghcr.io/lldap/lldap:stable` (sha256 hash of `7df30065344c5b7f73bae2591db779460ae937e39e11b4a5d1adeb91082ed97e` which is for `amd64`).

Redacted docker env file:

```env
LLDAP_VERBOSE=true
LLDAP_LDAP_HOST=0.0.0.0
LLDAP_LDAP_PORT=3890
LLDAP_HTTP_HOST=0.0.0.0
LLDAP_HTTP_PORT=17170
LLDAP_HTTP_URL=https://example.com
LLDAP_JWT_SECRET=REDACTED
LLDAP_LDAP_BASE_DN=dc=example,dc=com
LLDAP_LDAP_USER_DN=example
LLDAP_LDAP_USER_EMAIL=example@example.com
LLDAP_LDAP_USER_PASS=REDACTED
LLDAP_DATABASE_URL=sqlite:///data/users.db?mode=rwc
#LLDAP_KEY_FILE=
LLDAP_KEY_SEED=REDACTED
#LLDAP_IGNORED_USER_ATTRIBUTES=[ "sAMAccountName" ]
#LLDAP_IGNORED_GROUP_ATTRIBUTES=[ "mail", "userPrincipalName" ]
LLDAP_SMTP_OPTIONS__ENABLED_PASSWORD_RESET=true
LLDAP_SMTP_OPTIONS__SERVER=smtp.mailbox.org
LLDAP_SMTP_OPTIONS__PORT=465
LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS
LLDAP_SMTP_OPTIONS__USER=REDACTED
LLDAP_SMTP_OPTIONS__PASSWORD=REDACTED
LLDAP_SMTP_OPTIONS__FROM=Account Service <accounts@example.com>
LLDAP_SMTP_OPTIONS__REPLY_TO=Do Not Reply <noreply@example.com>
LLDAP_LDAPS_OPTIONS__ENABLED=false
#LLDAP_LDAPS_OPTIONS__PORT=6360
#LLDAP_LDAPS_OPTIONS__CERT_FILE=
#LLDAP_LDAPS_OPTIONS__KEY_FILE=
```

**Comment by nitnelave** [comment]
Hey! At the top of the verbose logs, when you start LLDAP, you'll have the config printed. Can you post the SMTP section?

Note that if there is no email configured/email reset is not enabled, I think that's consistent with the logs you get.

**Comment by nitnelave** [comment]
(in particular, I think you'll see that the config option is "enable_password_reset" and your environment variable is "enabled_password_reset")

**Comment by francescor** [comment]
note for quick reader

in the above 

```
< LLDAP_SMTP_OPTIONS__ENABLED_PASSWORD_RESET=true
> LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
```
