### ISSUE TITLE
MultiArch ARM64 Support

### ISSUE THREAD

**Issue by xavier83** [nitnelave/lldap#79]
Would be great if the container images support MultiArch/ARM64 for running on arm64 embedded hardware like raspberry pi or arm64 based cloud instances.

**Comment by nitnelave** [comment]
Damn, I'm working on it but it's surprisingly difficult! Right now I'm hitting issues with musl versions for the time library (undefined reference to `__time64` & co). Something along these lines, maybe? https://stackoverflow.com/questions/61934997/undefined-reference-to-stat-time64-when-cross-compiling-rust-project-on-mu

**Comment by nitnelave** [comment]
@xavier83 Would you be okay with a non-dockerized version? Basically just the binary + compiled WASM, drop it anywhere and run it from there. That seems to be much easier to do than a docker image (although I guess you could also have a docker-in-docker to get `cross` to compile it?).

**Comment by nitnelave** [comment]
I'll see whether I do pre-compiled binary releases, but I'll anyway add instructions for cross-compiling to the README

**Comment by nitnelave** [comment]
Here are the cross-compile instructions, on the "mail" branch: https://github.com/nitnelave/lldap/tree/mail

They'll get merged into main when I merge the branch, and I'll probably do a release at that point with some precompiled binaries.

**Comment by martadinata666** [comment]
Sorry for bumping this as i interested in this, are we must going to musl ? i mean building via glibc prove to be faster and easier, yes it lost the `portability` thing because musl build is `static`, but i think it doesn't really worth to pursue.

**Comment by nitnelave** [comment]
So, with each release I provide a pre-compiled ARM binary that you can download. I don't provide a docker image because I couldn't figure out how to cross-compile inside docker, but I put instructions in the README on how to cross-compile it yourself, it's fairly straightforward.

**Comment by yamsu** [comment]
Unable to run the docker image on an Arm64 ubuntu 20.04 host. Using the example docker-compose.yml. I get the following error:
```
> docker-compose up
[+] Running 1/1
 ⠿ Container lldap-lldap-1  Recreated                                                      0.1s
Attaching to lldap-lldap-1
lldap-lldap-1  | exec /app/docker-entrypoint.sh: exec format error
lldap-lldap-1 exited with code 1
```

The same config, on an x86 ubuntu 20.04 host, works without trouble.

**Comment by martadinata666** [comment]
Currently only `:latest` tag support arm64 and armv7, as this is still testing purpose, please open issue or join discord if the lldap got issues.

**Comment by yamsu** [comment]
> Currently only `:latest` tag support arm64 and armv7, as this is still testing purpose, please open issue or join discord if the lldap got issues.

`nitnelave/lldap:latest` works on arm64, Thanks
updated docker-compose.yml accordingly

**Comment by nitnelave** [comment]
You can even use `:stable` now, there was a release!
