### ISSUE TITLE
Feature Request: set secrets from file

### ISSUE THREAD

**Issue by kaysond** [nitnelave/lldap#84]
A common feature in many docker containers (mariadb, all of lsio containers, authelia) is the ability to set secret configuration parameters, or configuration parameters in general, via a file. Users supply an env var such as `LLDAP_LDAP_USER_PASS_FILE` which contains the location of a file whose contents set the parameter.

In particular, this is useful because it enables you to employ docker secrets, which in turn allows you to store secrets in a completely encrypted manner, and doesn't depend on plaintext storage.

See:
* https://www.authelia.com/docs/configuration/secrets.html
* https://github.com/linuxserver/docker-jellyfin#environment-variables-from-files-docker-secrets
* https://github.com/docker-library/docs/tree/master/mariadb#environment-variables

**Comment by nitnelave** [comment]
This should be doable with a startup script. Do you want to have a go at it?

**Comment by kaysond** [comment]
Sure I can probably get to it over the holiday weekend at some point

**Comment by kaysond** [comment]
Closed by #89
