### ISSUE TITLE
Feature Request: versioned docker hub images

### ISSUE THREAD

**Issue by kaysond** [nitnelave/lldap#85]
For reproducible deployments, its necessary to have different image tags for each version. Without this, rollbacks in docker swarm or kubernetes aren't possible.

I realize its a bit early on in this project for versions, but I'm excited about its potential so I figured I'd put it here anyways! :)

You could even just start with a `0.0.1`

**Comment by nitnelave** [comment]
Hey there! Thanks for the issue :) There is already a tag for each release, it's just that the only tag so far is `mvp`.

But don't worry, it's already setup to create a tagged docker image whenever I do a semver push (tag `vx.x.x`), it just hasn't happened yet. I'll do a release soon-ish.

**Comment by nitnelave** [comment]
Here you go, a new release and plenty of tags on Docker :) (stable, v0, v0.2, v0.2.0, latest)
https://github.com/nitnelave/lldap/releases/tag/v0.2.0
